### ISSUE TITLE
导入数据库出错

### ISSUE THREAD

**Issue by napoguolun** [InJeCTrL/WeFile#1]
--
-- Database: `wefile`
--

DELIMITER $$
--
-- 存储过程
--
CREATE DEFINER=`root`@`localhost` PROCEDURE `FileClear`()
    MODIFIES SQL DATA
    SQL SECURITY INVOKER
DELETE
FROM file
WHERE RestTime = 0$$
MySQL 返回： 文档

#1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation

**Comment by InJeCTrL** [comment]
RDS mysql中没有super权限，移除“DEFINER=root@localhost”即可导入。
